import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lewis Quinn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-zinc-900 '>
        <section className=' min-h-screen flex'>
          <div className=' m-auto h-100  '>
            <h1 className=' text-6xl text-white uppercase '>
              Lewis Quinn 
            </h1>
            <h2 className=' text-3xl text-white mt-2 mb-8 uppercase '>
              Front End Developer
            </h2>

            <button className=' bg-transparent uppercase text-sm text-white px-7 py-2 rounded-3xl border-solid border-2 border-white '>
              <a href='/about'>
                About
              </a>
            </button>

            <button className=' bg-transparent uppercase text-sm text-white px-7 py-2 rounded-3xl border-solid border-2 border-white ml-4 '>
              <Link href='/postCarouselPage'>
                Contact
              </Link>
            </button>

          </div>
        </section>
      </main>
    </>
  )
}
