import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PostCarousel from '../components/projectCarousel'
import Carousel from "../components/carousel";
import { createClient } from 'contentful'

// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, {Autoplay} from 'swiper';

// Import Swiper styles
import 'swiper/css';


export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  })

  const res = await client.getEntries({ content_type: "folioPost" })

  return {
    props: {
      folioPosts: res.items
    },
    revalidate: 1
  }
}


export default function PostCarouselPage({ folioPosts }) {
  console.log(folioPosts)

  SwiperCore.use([Autoplay])

    return (
      <>
        <Head>
          <title>Lewis Quinn - Projects</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className=' bg-zinc-900 '>
          <section className=' min-h-screen'>
              <Swiper
                  slidesPerView={1}
                  loop={true}
              //     autoplay={{
              //         delay:2000
              //   }}
              >
              <div>
                  {folioPosts.map(folioPost => (
                    <SwiperSlide>
                        <PostCarousel key={folioPost.sys.id} folioPost={folioPost}/>
                    </SwiperSlide>
                  ))}
              </div> 
            </Swiper>
          </section>
        </main>
      </>
    )
  }